class BotButton:
    add_account_name = "میخوام براش یه اسم انتخاب کنم"
    add_account_number = "شماره حسابش رو هم اضافه میکنم"
    main_menu = "منوی اصلی"
    no_change_it = "نه صبر کن! تغییرش میدم"
    yes_add = "بله، اضافه بشه"
    cash = "پول نقد"
    account = "حساب بانکی"
    financial_budgeting = "بودجه بندی مالی"
    financial_report = "گزارش مالی"
    account_list = "لیست حساب ها"
    new_account = "تعریف حساب جدید"
    new_cost = "دخل و خرج جدید"
    starter = "بزن بریم"
